keycloak:
  image:
    repository: quay.io/keycloak/keycloak
    tag: 24.0.4
    pullPolicy: Always
  settings:
    keycloakAdminUser: admin
    keycloakAdminPassword: admin
    keycloakHost: id.mydomain.local

pvc:
  size: 50Mi
  storageClassName: standard
