ingress:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  ingressClassName: nginx

keycloak:
  image:
    repository: quay.io/keycloak/keycloak
    tag: 24.0.4
    pullPolicy: Always
  settings:
    keycloakAdminUser: admin
    keycloakAdminPassword: admin
    keycloakHost: id.mydomain.local

pvc:
  annotations:
    helm.sh/resource-policy: "keep"
  size: 50Mi
  storageClassName: standard
