#publicURL: ""
publicURL: "https://meet.minikube.loc"

#turnHost: ""
turnHost: "turn.minikube.loc"

websockets:
  colibri:
    enabled: false
  xmpp:
    #enabled: false
    enabled: true

## #############################################################################
## Web configuration
## #############################################################################
web:
  image:
    repository: ghcr.io/jitsi-contrib/hardened-images/web

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault

  extraEnvs:
    # https://github.com/just-containers/s6-overlay/issues/600
    S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES: "1"

  extraVolumes:
    - name: run
      emptyDir:
        sizeLimit: 32Mi
    - name: tmp
      emptyDir:
        sizeLimit: 32Mi

  extraVolumeMounts:
    - name: run
      mountPath: /run
    - name: tmp
      mountPath: /tmp

  ingress:
    # emrah (ingress)
    #enabled: false
    enabled: true

    #annotations: {}
    annotations:
      cert-manager.io/cluster-issuer: "selfsigned-issuer"

    hosts:
      - host: meet.minikube.loc
        paths: ["/"]

    #tls: []
    tls:
      - secretName: jitsi-tls
        hosts:
          - meet.minikube.loc

  service:
    port: 8000

  livenessProbe:
    httpGet:
      path: /
      port: 8000

  readinessProbe:
    httpGet:
      path: /
      port: 8000


## #############################################################################
## Prosody configuration
## #############################################################################
prosody:
  image:
    repository: ghcr.io/jitsi-contrib/hardened-images/prosody

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault

  extraEnvs:
    # https://github.com/just-containers/s6-overlay/issues/600
    S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES: "1"

  extraVolumes:
    - name: run
      emptyDir:
        sizeLimit: 32Mi
    - name: tmp
      emptyDir:
        sizeLimit: 32Mi
    - name: storage
      emptyDir:
        sizeLimit: 32Mi

  extraVolumeMounts:
    - name: run
      mountPath: /run
    - name: tmp
      mountPath: /tmp
    - name: storage
      mountPath: /var/lib/prosody


## #############################################################################
## Jicofo configuration
## #############################################################################
jicofo:
  image:
    repository: ghcr.io/jitsi-contrib/hardened-images/jicofo

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault

  extraEnvs:
    # https://github.com/just-containers/s6-overlay/issues/600
    S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES: "1"

  extraVolumes:
    - name: run
      emptyDir:
        sizeLimit: 32Mi
    - name: tmp
      emptyDir:
        sizeLimit: 32Mi

  extraVolumeMounts:
    - name: run
      mountPath: /run
    - name: tmp
      mountPath: /tmp

## #############################################################################
## JVB configuration
## #############################################################################
jvb:
  image:
    repository: ghcr.io/jitsi-contrib/hardened-images/jvb

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault

  extraEnvs:
    # https://github.com/just-containers/s6-overlay/issues/600
    S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES: "1"

  extraVolumes:
    - name: run
      emptyDir:
        sizeLimit: 32Mi
    - name: tmp
      emptyDir:
        sizeLimit: 32Mi

  extraVolumeMounts:
    - name: run
      mountPath: /run
    - name: tmp
      mountPath: /tmp

  publicIPs:
    - 172.18.18.21

  #stunServers: "meet-jit-si-turnrelay.jitsi.net:443"
  stunServers: ""

  #useInternalStun: true
  useInternalStun: false

  #useHostPort: false
  useHostPort: true
  UDPPort: 10000

  service:
    #enabled: true
    enabled: false
