apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.name-app" . }}
  labels:
    app: {{ include "keycloak.name-app" . }}
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ include "keycloak.name-app" . }}
  type: ClusterIP
