apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "keycloak.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "keycloak.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ include "keycloak.name" . }}
        image: {{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}
        imagePullPolicy: {{ .Values.keycloak.image.pullPolicy }}
        env:
        - name: DB_VENDOR
          value: h2
        - name: KEYCLOAK_USER
          value: {{ .Values.keycloak.settings.keycloakUser | quote }}
        - name: KEYCLOAK_PASSWORD
          value: {{ .Values.keycloak.settings.keycloakPassword | quote }}
        volumeMounts:
        - name: keycloak-data
          mountPath: /opt/keycloak/data
      volumes:
      - name: keycloak-data
        persistentVolumeClaim:
          claimName: keycloak-pvc
