apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "keycloak.name-pvc" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.size | quote }}
  storageClassName: {{ .Values.pvc.storageClassName | quote }}
