apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "keycloak.name-pvc" . }}
  annotations:
    {{- with .Values.pvc.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.size | quote }}
  storageClassName: {{ .Values.pvc.storageClassName | quote }}
