# ------------------------------------------------------------------------------
# DEFAULT JITSI CONFIGURATION
# ------------------------------------------------------------------------------
.jitsiDefaults: &jitsiDefaults
  publicURL: "https://meet.minikube.loc"

  excalidraw:
    enabled: true

  etherpad:
    enabled: true

  jvb:
    replicaCount: 1
    portRangeSize: 3
    publicIPs:
    - 172.18.18.21

# ------------------------------------------------------------------------------
# SHARD CONFIGURATION
# ------------------------------------------------------------------------------
shard0:
  enabled: true
  <<: *jitsiDefaults

shard1:
  enabled: true
  <<: *jitsiDefaults
 
shard2:
  enabled: true
  <<: *jitsiDefaults

# ------------------------------------------------------------------------------
# HAPROXY CONFIGURATION
# ------------------------------------------------------------------------------
haproxy:
  enabled: true
  replicaCount: 2

  ingress:
    #enabled: false
    enabled: true
    ingressClassName: "nginx"
    #annotations:
    annotations:
      cert-manager.io/cluster-issuer: "selfsigned-issuer"
    host: "meet.minikube.loc"
    paths:
      - "/"
    tls:
      #enabled: false
      enabled: true
      secretName: "jitsi-web-tls"

  gateway:
    enabled: false
    gatewayClassName: "envoy-gateway-class"
    #annotations:
    annotations:
      cert-manager.io/cluster-issuer: "selfsigned-issuer"
    host: "meet.minikube.loc"
    paths:
      - "/"
    tls:
      #enabled: false
      enabled: true
      secretName: "jitsi-web-tls"
